### ISSUE TITLE
Eslint rule Error when lint:fix command

### ISSUE THREAD

**Issue by charles0122** [chodocs/chodocs#273]
## 环境
node : 18.10.0
OS: windows 11
编辑器: vscode

## 操作

1. clone
2. pnpm i
3. pnpm lint:fix

## 出错命令
```
pnpm lint:fix
```

## 错误日志

```error.log
Oops! Something went wrong! :(

ESLint: 8.39.0

TypeError: Error while loading rule 'unicorn/no-instanceof-array': Cannot destructure property 'parserServices' of 'context.sourceCode' as it is undefined. 
Occurred while linting D:\CodeProjects\chodocs\.eslintrc.js
    at Object.wrapped [as create] (D:\CodeProjects\chodocs\node_modules\.pnpm\eslint-plugin-unicorn@48.0.1_eslint@8.39.0\node_modules\eslint-plugin-unicorn\rules\utils\rule.js:140:10)
    at createRuleListeners (D:\CodeProjects\chodocs\node_modules\.pnpm\eslint@8.39.0\node_modules\eslint\lib\linter\linter.js:869:21)
    at D:\CodeProjects\chodocs\node_modules\.pnpm\eslint@8.39.0\node_modules\eslint\lib\linter\linter.js:1035:110
    at Array.forEach (<anonymous>)
    at runRules (D:\CodeProjects\chodocs\node_modules\.pnpm\eslint@8.39.0\node_modules\eslint\lib\linter\linter.js:972:34)
    at Linter._verifyWithoutProcessors (D:\CodeProjects\chodocs\node_modules\.pnpm\eslint@8.39.0\node_modules\eslint\lib\linter\linter.js:1324:31)
    at Linter._verifyWithoutProcessors (D:\CodeProjects\chodocs\node_modules\.pnpm\eslint-plugin-eslint-comments@3.2.0_eslint@8.39.0\node_modules\eslint-plugin-eslint-comments\lib\utils\patch.js:166:36)
    at callOriginalVerify (D:\CodeProjects\chodocs\node_modules\.pnpm\eslint-plugin-html@7.1.0\node_modules\eslint-plugin-html\src\index.js:130:14)
    at Linter.<computed> (D:\CodeProjects\chodocs\node_modules\.pnpm\eslint-plugin-html@7.1.0\node_modules\eslint-plugin-html\src\index.js:140:14)
    at Linter._verifyWithConfigArray (D:\CodeProjects\chodocs\node_modules\.pnpm\eslint@8.39.0\node_modules\eslint\lib\linter\linter.js:1699:21)
```

**Comment by Chocolate1999** [comment]
我在 mac 上用 v18.10.0 试了下没问题的，我回家用 windows 电脑再试试看

**Comment by Chocolate1999** [comment]
Hi，我在 windows 电脑上试了下确实会有 eslint 问题，可能与 eslint 版本有关系。但并不打算修复这个问题，这只是一个文档项目，并不是文档的主题开发，在 mac 上是没有问题的，我也暂不打算使用 windows 开发，暂不会花时间在这上面修改，如果你解决了 windows 上问题，欢迎提供修改代码。

当下，我会在之后关掉当前 Issue。
